name: Lint
on: [pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.7.0
            - name: Install modules
              run: yarn install
            - name: Run ESLint
              run: yarn run lint:eslint
